
version: "3.7"

services:
  lets-nginx:
    image: smashwilson/lets-nginx
    restart: always
    volumes:
      - ./lets-nginx/cache:/cache
      - ./lets-nginx/letsencrypt:/etc/letsencrypt
    environment:
      - EMAIL=${LETS_ENCRYPT_EMAIL}
      - DOMAIN=${LETS_ENCRYPT_DOMAIN}
      - STAGING=${LETS_ENCRYPT_STAGING}
      - UPSTREAM=risotto-backend:${BACKEND_PORT}
    depends_on:
      - risotto-backend
    ports:
      - "80:80"
      - "443:443"

  risotto-backend:
    container_name: risotto-backend-prod
    environment:
      - PORT=${BACKEND_PORT}
    build:
      context: ..
      dockerfile: docker/Dockerfile
