FROM python:3.8.5-slim-buster

ENV DEBIAN_FRONTEND=noninteractive

# Install other dependencies
WORKDIR /code

COPY requirements.txt .
RUN pip install -r requirements.txt

# Flask environment variables
ENV FLASK_APP=risotto
ENV FLASK_ENV=development
EXPOSE 5000

CMD ["./scripts/runserver-dev.sh"]